# SPDX-License-Identifier: MIT
# Copyright (C) 2026 OpenCCU-Loom authors.

"""
Typed events emitted by the openccu-loom daemon over WebSocket.

Each ``WsEnvelope`` arriving on the wire is converted into a concrete
:class:`LoomEvent` subclass via :func:`event_from_envelope`. Consumers
subscribe to a specific subclass on the :class:`EventBus` and receive
only matching events — typed all the way through.

Unknown ``type`` strings (forward-compatibility with future daemon
versions) become :class:`UnknownLoomEvent` so the stream never drops
on the floor.
"""

from __future__ import annotations

from openccu_loom_client.events.bus import EventBus, SubscriptionGroup, UnsubscribeCallback
from openccu_loom_client.events.synthetic import (
    AuthFailedEvent,
    ConnectionStateChangedEvent,
    DataPointsCreatedEvent,
    OptimisticRollbackEvent,
    new_auth_failed_event,
    new_connection_state_changed_event,
    new_data_points_created_event,
    new_optimistic_rollback_event,
)
from openccu_loom_client.events.types import (
    AddonUpdateStateChangedEvent,
    AlarmCountdownEvent,
    AlarmHealthChangedEvent,
    AlarmJournalAppendedEvent,
    AlarmNotificationEvent,
    AlarmPanelChangedEvent,
    AlarmReadinessChangedEvent,
    AlarmReminderEvent,
    AlarmStateChangedEvent,
    AlarmTriggeredEvent,
    AlarmWalkTestProgressEvent,
    CentralReadinessChangedEvent,
    CentralStateChangedEvent,
    CustomDataPointStateChangedEvent,
    DaemonStatusChangedEvent,
    DataPointValueChangedEvent,
    DeviceAvailabilityChangedEvent,
    DeviceCreatedEvent,
    DeviceMetadataChangedEvent,
    DeviceReleasedEvent,
    DeviceRemovedEvent,
    HubAlarmMessageCountChangedEvent,
    HubConnectivityChangedEvent,
    HubInboxChangedEvent,
    HubMetricsChangedEvent,
    HubServiceMessageCountChangedEvent,
    HubSystemUpdateChangedEvent,
    InstallModeChangedEvent,
    LoomEvent,
    MatterCommissioningProgressEvent,
    MatterCommissioningWindowOpenedEvent,
    MatterEndpointAssembledEvent,
    MatterExposableChangedEvent,
    MatterFabricAddedEvent,
    MatterFabricRemovedEvent,
    ProgramChangedEvent,
    ProgramExecutedEvent,
    ScheduleChangedEvent,
    SecurityClassChangedEvent,
    SecurityFaultChangedEvent,
    SecurityNotificationEvent,
    SecurityStateChangedEvent,
    SecurityZoneChangedEvent,
    SystemStatusChangedEvent,
    SysvarChangedEvent,
    UnknownLoomEvent,
    event_from_envelope,
)

__all__ = [
    # General
    "AddonUpdateStateChangedEvent",
    "AlarmCountdownEvent",
    "AlarmHealthChangedEvent",
    "AlarmJournalAppendedEvent",
    "AlarmNotificationEvent",
    "AlarmPanelChangedEvent",
    "AlarmReadinessChangedEvent",
    "AlarmReminderEvent",
    "AlarmStateChangedEvent",
    "AlarmTriggeredEvent",
    "AlarmWalkTestProgressEvent",
    "AuthFailedEvent",
    "CentralReadinessChangedEvent",
    "CentralStateChangedEvent",
    "ConnectionStateChangedEvent",
    "CustomDataPointStateChangedEvent",
    "DaemonStatusChangedEvent",
    "DataPointValueChangedEvent",
    "DataPointsCreatedEvent",
    "DeviceAvailabilityChangedEvent",
    "DeviceCreatedEvent",
    "DeviceMetadataChangedEvent",
    "DeviceReleasedEvent",
    "DeviceRemovedEvent",
    "EventBus",
    "HubAlarmMessageCountChangedEvent",
    "HubConnectivityChangedEvent",
    "HubInboxChangedEvent",
    "HubMetricsChangedEvent",
    "HubServiceMessageCountChangedEvent",
    "HubSystemUpdateChangedEvent",
    "InstallModeChangedEvent",
    "LoomEvent",
    "MatterCommissioningProgressEvent",
    "MatterCommissioningWindowOpenedEvent",
    "MatterEndpointAssembledEvent",
    "MatterExposableChangedEvent",
    "MatterFabricAddedEvent",
    "MatterFabricRemovedEvent",
    "OptimisticRollbackEvent",
    "ProgramChangedEvent",
    "ProgramExecutedEvent",
    "ScheduleChangedEvent",
    "SecurityClassChangedEvent",
    "SecurityFaultChangedEvent",
    "SecurityNotificationEvent",
    "SecurityStateChangedEvent",
    "SecurityZoneChangedEvent",
    "SubscriptionGroup",
    "SystemStatusChangedEvent",
    "SysvarChangedEvent",
    "UnknownLoomEvent",
    "UnsubscribeCallback",
    "event_from_envelope",
    "new_auth_failed_event",
    "new_connection_state_changed_event",
    "new_data_points_created_event",
    "new_optimistic_rollback_event",
]
