# SPDX-License-Identifier: MIT
# Copyright (C) 2026 OpenCCU-Loom authors.

"""Generated typing bindings for the openccu-loom daemon's wire contract.

Every module here is machine-generated from the daemon's committed
contract assets and regenerated by `make generate` (see `script/gen/`).
Nothing in this subpackage is hand-written, and nothing else in this
client may be generated — that split is what keeps a regeneration diff
reviewable.

Submodules:

- :mod:`openccu_loom_client.wire.enums` — every enum from the daemon's
  `pkg/hmenum` (generated from `assets/schemas/enums.json`).
- :mod:`openccu_loom_client.wire.rest` — Pydantic models for the REST
  surface (generated from `assets/openapi.yaml`).
- :mod:`openccu_loom_client.wire.ws` — the WebSocket envelope plus the
  push payloads, which are re-exported from
  :mod:`openccu_loom_client.wire.rest` because the daemon declares them
  in one schema document.

These modules used to ship as the separate distribution
`openccu-loom-types`. They are here because the split cost a release of
its own for every daemon release without ever carrying a hand-written
line, and because no consumer imported the package directly.

`VERSION` is the last version that distribution published; it is kept so
a consumer that recorded it can still recognise the generation lineage.
The client's own version is `openccu_loom_client.const.VERSION`.
"""

from typing import Final

from openccu_loom_client.wire.const import DAEMON_API_VERSION, SCHEMA_DIGEST, VERSION

WIRE_VERSION: Final = VERSION

__all__ = ["DAEMON_API_VERSION", "SCHEMA_DIGEST", "VERSION", "WIRE_VERSION"]
